---
title: "Incentivos al Retiro"
output: 
  pdf_document: 
    toc: true
    toc_depth: 3
    keep_tex: yes
bibliography: referencias.bib

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introducción

- Importancia de alargar vida laboral. (OCDE 2011).

Atalay

Population aging poses an important challenge to the fiscal sustainability of social security systems in many industrialized economies. In addressing these challenges governments around the world continue to implement reforms to their social security programs. Restruc- turing the pension system, changing the level of benefit payments, and tightening access such as by increasing the eligibility age, are common examples of reforms that have recently been implemented.



# Marco Conceptual


## Impacto de la Seguridad Social en la oferta de trabajo

Atalay

The theoretical literature on the incentive effects of social security show that workers’ retirement decisions are influenced through two main channels. The first is by directly changing the life-time income or expected wealth of an individual. If the program benefit exceeds the individual’s contribution to the program, existence of the program increases the life-time income of the individual and therefore reduces the labour supply of the individual on the assumption that leisure is a normal good. This is known as the “wealth effect” of the program. 

The second channel operates when social security benefit payments increase with contributory earnings. In this case, an extra year of work also increases the future stream of expected social security benefits. When considering the optimal timing of retirement, workers will take account of the effect of an extra year of work on the level of retirement income when s/he eventually retires. 

- Modelo de oferta de trabajo y retiro (@cribb16). Trade-off entre consumo y ocio.
- Canales de impacto de la SS a la oferta laboral
  - Efecto sustitución (accrual)
  - Efecto riqueza.
  
Gruber and Wise (2004) and Samwick (1998) argue that the accrual effect is the main driving source of retirement behavior in the reforms. 

Cribb:

Gruber and Wise (2004) surveyed evidence on eleven developed countries and highlighted the fact that labor force exits are concentrated around legislated early and normal retirement ages and tend to be larg- er than can be explained by the pure financial incentives associated with retiring at these ages.

Most of the early papers that attempted to simulate the impact of moving these early and normal retirement ages on labor force participation relied on using out-of-sample predictions. Papers simulating changes in early and normal retirement ages in the US suggested quite large effects on retirement ages.

However, while the effects estimated in these ex ante simulations were quite large, if anything the results of ex post evaluations suggests even larger effects. 

More recently, there have been a growing number of reforms around the world, which have increased pension ages. Therefore, ex post evaluations have become more common in the literature.


Women's economic activity could be affected by an increase in the ERA through four main mechanisms. First, increasing the ER



A will have some effect on individuals' marginal financial incentives to work, through changing marginal tax rates and eligibility for out-of-work ben- efits. This channel will be significantly less important in the UK than it is in some other countries because there is no earnings test for state pen- sion receipt in the UK.


Second, the increase in the ERA reduces the length of time that indi- viduals receive state pension income for and thus reduces their lifetime wealth; this will tend to increase labor supply.

Third, individuals who are credit constrained may have to continue working during the period when they are no longer able to receive their state pension in order to finance their consumption.

Fourth, the ERA may provide a signal about the ‘appropriate’ age at which to retire


- Otros factores
  - Efecto señalización
  - Restricciones de liquidez
  - Oportunidades laborales
  - Impacto sobre todo el hogar.

## Parámetros de la SS

- Edad Mínima de Retiro, Edad Normal de Retiro, Ajustes Actuariales.
- Hay varios más en el glosario pero nos centramos en estos.



## Midiendo los incentivos de la SS

- $ SSW $, Accrual, $ITAX$.


Para medir estos incentivos empíricamente, se calcula la riqueza de la seguridad social (SSW). Esta medida compara los ingresos que el trabajador recibe por trabajar con los cambios en el flujo de prestaciones que le paga el sistema de jubilaciones. 









Para resolver esta limitación, se propone la medida de _Peak Value_, que calcula 

- Peak Value, Option Value


Consider that an individual takes the decision regarding the optimal date of retirement entry according to the Option Value Model of Stock and Wise (1990), i.e. she compares all possible future streams of utility from income and leisure and delays retirement entry if she can thereby receive a higher stream of utility. 
In this framework, retiring at any early date s instead of any later dater t has four effects: (i) it lowers utility due to a loss of wage earnings during the period between s and t, (ii) it increases utility from leisure during s and t, (iii) it lengthens the period of benefit receipt, thereby raising utility according to the amount of benefits that are paid between s and t, and (iv) it changes the expected present value of future benefits during the remaining lifetime according to the pension formula. Hence, retiring at date s instead of t will be preferred only if the loss in wage income is at least outweighed by (a) the utility from leisure between s and t, (b) the retirement income received between s and t, plus (b) the difference in the present values of future income if the individual retires at date s instead of date t.

# Literatura empírica

## Primeros Trabajos


- Efectos de la $SSW$ y del Accrual. 

Hanel

One strand of the literature deals with the effect of expected income from social security or pension benefits (i.e. the level of social security or pension wealth) on the retirement decision. Classical life-cycle-models used for example by Gordon and Blinder (1980) or Gustman and Steinmeier (1986) show that the amount of provided benefits compared to potential wages has an influence on the retirement decision of an individual maximizing utility from income and leisure. 

Hurd (1990a) examined the peak in retirement entries in the United States at age 62, when benefit receipt is first available. This peak has grown over time with growing social security benefits. Blau (1994) estimated hazard rates into retirement dependent on social security wealth and found a strong connection between benefit levels and exit rates. A well-known study to be mentioned is conducted by Krueger and Pischke (1992). 

There is a strong agreement across the literature that pension accruals fundamentally influence the retirement decision. Samwick (1998) compared the effect of the level of social security wealth and accruals in social security wealth and found the impact of accruals to be the central determinant of the timing of retirement.


### Comentarios y Problemas sobre estos trabajos

Atalay

The majority of the empirical research attempting to estimate the ef- fect of social security incentives on retirement is based on cross sectional variation. These studies, summarized in the detailed surveys by Coile and Gruber (2007) and Chan and Stevens (2004), typically find strong effects of social security incentives on retirement deci- sion. A limitation with this approach is that since the social security policy is the same for everyone at a point in time, identification may be undermined by the correlation between program incentives and tastes for retirement. Therefore it is very difficult to reliably disen- tangle the effect of social security program parameters from differences in preferences across individuals, or from general trends in retirement and benefit levels over time.

Atalay

A well known example of this approach is Krueger and Pischke (1992) in which they investigate a change to U.S. Social Security pro- visions in 1977. In contrast to many cross sectional studies, Krueger and Pischke (1992) find a weak relationship between social security wealth and labour supply.

## Políticas de las últimas décadas

@NBERbors-1

Entre 1980 y 2018, la EMR subió en Bélgica, Dinamarca, Francia, Alemania, Japón, Holanda, España, Suecia y el Reino Unido (@borsch20). Como veremos más adelante, las variaciones de este parámetro de política pueden usarse para estimar la respuesta en los trabajadores con precisión.

La ENR también subió generalizadamente en los países de la OCDE. 

Los ajustes actuariales penalizan a los trabajadores que se retiran antes de la ENR. Dado que al postergar un año el retiro, el trabajador contribuye un año más a la seguridad social y recibe un año menos de prestaciones, es usual que el valor de estas prestaciones sea mayor cuanto más postergue el trabajaro el acceso a las mismas.

## Resultados de estas políticas

Atalay

investigate two issues: (i) to what extent this policy reform contributed to an increase in the labour force participation of women, and (ii) the degree to which the reform had an unintended side-effect of inducing participation in alternative government programs, especially the Disability Support Pension.

The key challenge in the empirical literature is to find a substantial and plausibly exoge- nous variation in the social security system to identify and gauge the behavioural impacts of public pensions.

### Ajustes Actuariales y Edad Normal de Retiro

### Edad Mínima de Retiro

## Lecciones para Uruguay

- La edad mínima de jubilación es un instrumento altamente eficaz para prolongar la vida laboral de los mayores. Efecto señalización es parte del impacto.
- Los incentivos actuariales también funcionan.
- Jubilaciones mínimas pueden ser un incentivo a salir temprano del mercado a pesar de los ajustes actuariales.
- Ojo con los otros programas.
- Salud y educación, restricciones en las oportunidades de empleo.

# Glosario

Edad Efectiva de Retiro

:   Es la edad a la que un individuo empieza a recibir prestaciones del sistema de seguridad social.

Edad Mínima de Retiro

:   Es la menor edad a la que un trabajador puede aplicar a un programa de seguridad social. Es usual que en estos casos las prestaciones se vean reducidas frente a las recibidas en la edad normal de retiro.

Retiro Temprano

: Es la práctica de acogerse a los beneficios de la seguirdad social antes de la edad normal de retiro.

Prueba de Ingresos

: Es un límite a los ingresos que puede tener alguien que recibe prestaciones del sistema de segurida social.

Impuestos Implícitos

:  Es el impuesto implícito que enfrenta un trabajador cuando, pudiendo recibir una prestación del sistema de seguirdad social, decide seguir trabajando y sus beneficios futuros no son compensados.



# Referencias

